USE [master]
GO

/****** Object:  Database [cardtransactions]    Script Date: 8.01.2023 20:11:53 ******/
CREATE DATABASE [cardtransactions]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cardtransactions', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\cardtransactions.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cardtransactions_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\cardtransactions_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cardtransactions].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cardtransactions] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cardtransactions] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cardtransactions] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cardtransactions] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cardtransactions] SET ARITHABORT OFF 
GO

ALTER DATABASE [cardtransactions] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cardtransactions] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cardtransactions] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cardtransactions] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cardtransactions] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cardtransactions] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cardtransactions] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cardtransactions] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cardtransactions] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cardtransactions] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cardtransactions] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cardtransactions] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cardtransactions] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cardtransactions] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cardtransactions] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cardtransactions] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cardtransactions] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cardtransactions] SET RECOVERY FULL 
GO

ALTER DATABASE [cardtransactions] SET  MULTI_USER 
GO

ALTER DATABASE [cardtransactions] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cardtransactions] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cardtransactions] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cardtransactions] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [cardtransactions] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cardtransactions] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [cardtransactions] SET QUERY_STORE = OFF
GO

ALTER DATABASE [cardtransactions] SET  READ_WRITE 
GO


USE [cardtransactions]
GO

/****** Object:  Table [dbo].[Sale]    Script Date: 8.01.2023 20:12:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sale](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TransactionId] [nvarchar](12) NOT NULL,
	[Timestamp] [datetime] NOT NULL,
	[Cardholder] [nvarchar](1024) NOT NULL,
	[PAN] [nvarchar](50) NOT NULL,
	[ExpireDate] [nvarchar](4) NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[Currency] [nvarchar](3) NOT NULL,
	[ResponseCode] [nvarchar](2) NOT NULL,
	[ErrorMessage] [nvarchar](max) NULL,
	[CardType] [nvarchar](10) NULL,
 CONSTRAINT [PK_Sale] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



